# Generated by Django 5.0.7 on 2024-12-17 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userODS', '0002_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('user', 'User'), ('admin', 'Admin'), ('manager', 'Manager')], max_length=10, null=True),
        ),
    ]
