# Generated by Django 5.0.7 on 2024-12-17 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userODS', '0003_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('user', 'User'), ('admin', 'Admin'), ('manager', 'Manager')], default='User', max_length=10, null=True),
        ),
    ]
