# Generated by Django 5.0.7 on 2024-12-18 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userODS', '0004_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
