# Generated by Django 5.0.7 on 2024-12-26 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userODS', '0006_user_access_code_user_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='userODS.profile')),
                ('phonee', models.CharField(max_length=50)),
            ],
            bases=('userODS.profile',),
        ),
        migrations.CreateModel(
            name='HotelManager',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='userODS.profile')),
                ('hotel_name', models.CharField(max_length=200)),
            ],
            bases=('userODS.profile',),
        ),
    ]
