# Generated by Django 5.0.7 on 2024-12-26 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userODS', '0007_customer_hotelmanager'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='Manager',
        ),
    ]
