# Generated by Django 5.0.7 on 2024-12-26 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userODS', '0008_rename_customer_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='profile_ptr',
        ),
        migrations.DeleteModel(
            name='HotelManager',
        ),
        migrations.DeleteModel(
            name='Manager',
        ),
    ]
