# Generated by Django 5.0.7 on 2024-12-26 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userODS', '0010_hotelmanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HotelManager',
        ),
    ]
