# Generated by Django 5.0.7 on 2024-12-27 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userODS', '0012_hotelmanager_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('customer', 'Customer'), ('employee', 'Employee')], max_length=10, null=True),
        ),
    ]
