# Generated by Django 5.0.7 on 2024-12-27 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userODS', '0013_profile_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user_type',
        ),
        migrations.AddField(
            model_name='hotelmanager',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('customer', 'Customer'), ('employee', 'Employee')], default='Employee', max_length=10),
        ),
    ]
