# Generated by Django 5.0.7 on 2024-12-27 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userODS', '0014_remove_profile_user_type_hotelmanager_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelmanager',
            name='user_type',
            field=models.CharField(default='Employee', max_length=10),
        ),
    ]
