# Generated by Django 5.0.7 on 2024-12-27 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userODS', '0015_alter_hotelmanager_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelmanager',
            name='user_type',
        ),
    ]
