# Generated by Django 5.0.7 on 2024-12-28 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userODS', '0016_remove_hotelmanager_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelmanager',
            name='hotel_name',
        ),
    ]
