# Generated by Django 5.0.7 on 2024-12-28 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userODS', '0017_remove_hotelmanager_hotel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelmanager',
            name='hotel_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
