# Generated by Django 5.0.7 on 2024-12-28 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0039_rename_roomm_service_room'),
        ('userODS', '0018_hotelmanager_hotel_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelmanager',
            name='hotel_name',
        ),
        migrations.AddField(
            model_name='hotelmanager',
            name='hotel',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel'),
        ),
    ]
