# Generated by Django 5.0.7 on 2025-06-18 15:21

import userODS.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userODS', '0019_remove_hotelmanager_hotel_name_hotelmanager_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=userODS.models.user_directory_path),
        ),
    ]
