# Generated by Django 5.0.7 on 2025-06-18 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userODS', '0020_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
    ]
