# Generated by Django 5.0.7 on 2024-10-17 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0009_staffonduty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtype',
            name='typee',
            field=models.CharField(default='VIP', max_length=10),
        ),
    ]
