# Generated by Django 5.0.7 on 2024-10-17 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0010_alter_roomtype_typee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='room_type',
        ),
    ]
