# Generated by Django 5.0.7 on 2024-12-21 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0014_roomtype_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomtype',
            name='image',
        ),
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='room_gallery'),
        ),
    ]
