# Generated by Django 5.0.7 on 2024-12-21 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0015_remove_roomtype_image_room_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomtype',
            name='number_of_beds',
        ),
        migrations.RemoveField(
            model_name='roomtype',
            name='price',
        ),
        migrations.RemoveField(
            model_name='roomtype',
            name='room_capacity',
        ),
        migrations.AddField(
            model_name='room',
            name='room_capacity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
