# Generated by Django 5.0.7 on 2024-12-21 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0016_remove_roomtype_number_of_beds_remove_roomtype_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='room_capacity',
        ),
        migrations.AddField(
            model_name='roomtype',
            name='number_of_beds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='room_capacity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
