# Generated by Django 5.0.7 on 2024-12-21 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0017_remove_room_room_capacity_roomtype_number_of_beds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_capacity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
