# Generated by Django 5.0.7 on 2024-12-21 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0018_room_room_capacity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='room_capacity',
        ),
    ]
