# Generated by Django 5.0.7 on 2024-12-21 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0019_remove_room_room_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='n',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='p',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='room',
            name='room_c',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
