# Generated by Django 5.0.7 on 2024-12-22 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0020_room_n_room_p_room_room_c'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='room_type',
            field=models.ForeignKey(default='VIP', on_delete=django.db.models.deletion.CASCADE, to='hotel.roomtype'),
        ),
    ]
