# Generated by Django 5.0.7 on 2024-12-23 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0024_alter_booking_check_in_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='room_type',
        ),
    ]
