# Generated by Django 5.0.7 on 2024-12-23 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0029_alter_booking_room_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='room_type',
        ),
    ]
