# Generated by Django 5.0.7 on 2024-12-23 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0030_remove_booking_room_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='room_type',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
