# Generated by Django 5.0.7 on 2024-12-24 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0034_room_description_room_view'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='description',
        ),
        migrations.RemoveField(
            model_name='room',
            name='view',
        ),
    ]
