# Generated by Django 5.0.7 on 2024-12-24 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0035_remove_room_description_remove_room_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='view',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
