# Generated by Django 5.0.7 on 2024-12-25 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0037_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='hotel',
        ),
        migrations.RemoveField(
            model_name='service',
            name='room_type',
        ),
    ]
