# Generated by Django 5.0.7 on 2024-12-25 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0038_remove_service_hotel_remove_service_room_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='roomm',
            new_name='room',
        ),
    ]
