# Generated by Django 5.0.7 on 2025-01-06 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0039_rename_roomm_service_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='hotel_gallery'),
        ),
    ]
