# Generated by Django 5.0.7 on 2025-01-06 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0040_alter_hotel_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='image',
        ),
    ]
