# Generated by Django 5.0.7 on 2025-01-06 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0041_remove_hotel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='hotel_gallery'),
        ),
    ]
