# Generated by Django 5.0.7 on 2025-01-06 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0042_hotel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='hotels/'),
        ),
    ]
