# Generated by Django 5.0.7 on 2025-01-06 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0044_alter_hotel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='hotel_gallery'),
        ),
    ]
