# Generated by Django 5.0.7 on 2025-01-06 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0045_alter_hotel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
