# Generated by Django 5.0.7 on 2025-05-03 09:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0046_alter_hotel_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferManage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('offer_type', models.CharField(choices=[('Black Friday', 'Black Friday'), ('White Friday', 'White Friday'), ('Summer Start Offers', 'Summer Start Offers'), ('First-time', 'First-time')], default='Black Friday', max_length=100)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('start_date', models.DateTimeField(default=datetime.datetime.now)),
                ('end_date', models.DateTimeField(default=datetime.datetime.now)),
                ('conditions', models.TextField()),
            ],
        ),
    ]
