# Generated by Django 5.0.7 on 2025-05-05 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0047_offermanage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='room_type',
        ),
    ]
