# Generated by Django 5.0.7 on 2025-05-05 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0048_remove_room_room_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roomtype',
            options={},
        ),
        migrations.RemoveField(
            model_name='booking',
            name='room_type',
        ),
        migrations.RemoveField(
            model_name='roomtype',
            name='date',
        ),
        migrations.RemoveField(
            model_name='roomtype',
            name='hotel',
        ),
        migrations.RemoveField(
            model_name='roomtype',
            name='number_of_beds',
        ),
        migrations.RemoveField(
            model_name='roomtype',
            name='price',
        ),
        migrations.RemoveField(
            model_name='roomtype',
            name='room_capacity',
        ),
        migrations.RemoveField(
            model_name='roomtype',
            name='rtid',
        ),
        migrations.RemoveField(
            model_name='roomtype',
            name='slug',
        ),
    ]
