# Generated by Django 5.0.7 on 2025-05-05 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0049_alter_roomtype_options_remove_booking_room_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
