# Generated by Django 5.0.7 on 2025-05-06 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0050_room_room_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_status',
            field=models.CharField(choices=[('clean', 'Clean'), ('maintenance', 'Maintenance'), ('failure', 'Failure'), ('reserved', 'Reserved'), ('available', 'Available')], default='available', max_length=50),
        ),
    ]
