# Generated by Django 5.0.7 on 2025-05-08 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0051_room_room_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='offermanage',
            name='rooms',
            field=models.ManyToManyField(blank=True, to='hotel.room'),
        ),
    ]
