# Generated by Django 5.0.7 on 2025-05-08 12:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0052_offermanage_rooms'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='offermanage',
            name='created_by',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
