# Generated by Django 5.0.7 on 2025-05-08 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0053_offermanage_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offermanage',
            name='rooms',
        ),
    ]
