# Generated by Django 5.0.7 on 2025-05-08 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0054_remove_offermanage_rooms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offermanage',
            name='created_by',
        ),
    ]
