# Generated by Django 5.0.7 on 2025-06-04 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0056_hotel_stars'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='bookingcount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hotel',
            name='revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
