# Generated by Django 5.0.7 on 2025-06-05 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0057_hotel_bookingcount_hotel_revenue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='total_days',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
