# Generated by Django 5.0.7 on 2025-06-15 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0058_alter_booking_total_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='total_days',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
